module.exports = {
    ERROR_OUT_OF_BOUNDS_X: 0,
    ERROR_OUT_OF_BOUNDS_Y: 1,
    ERROR_ALREADY_SELECTED: 2,
    SUCCESS_MARKED_CELL: 3,
    VICTORY: 4,
    TIE: 5,
    INCREASING: 6,
    DECREASING: 7
};